### ISSUE TITLE
Error: Cannot find module 'function e(t, n, o) {function i(r,a){if(!n[r]){if(!t[r]){var l="function"...

### ISSUE THREAD

**Issue by og6k** [romeovs/gulp-browserify#1]
I am having an issue with this error when I use gulp browserify, with concatenate and uglify.

<pre>
gulp.task('js', function() {
        gulp.src(['/text-typer.js', '/bootstrap.min.js', 'moment.min.js', '/jquery.noty.js', '/default.js', '/top.js', '/jquery.fitvid.js', '/rrssb.min.js'])
            .pipe(browserify())
            .pipe(concat('footer.js'))
            .pipe(uglify())
            .pipe(rename('footer.min.js'))
            .pipe(gulp.dest('/js/'))
            .pipe(notify('js has just been concat and uglified'));
});

// the file path has been shortened for preview purposes
</pre>

When I run gulp js, everything seem to work smoothly on my website, but I get this error on my dev tool:

<pre>
[Error] Error: Cannot find module 'function e(t, n, o) {function i(r,a){if(!n[r]){if(!t[r]){var l="function"==typeof require&&require;if(!a&&l)return l(r,!0);if(s)return s(r,!0);throw new Error("Cannot find module '"+r+"'")}var u=n[r]={exports:{}};t[r][0].call(u.exports,function(e){var n=t[...
</pre>

I found a similar issue here: http://stackoverflow.com/questions/21514884/browserify-concatenated-browserified-files-error-prelude-js-vs-loading-sep,

But it didn't quite work for me. How do I solve this?

**Comment by romeovs** [comment]
You're probably using https://github.com/deepak1556/gulp-browserify and not this version of `gulp-browserify`. I made this one because the other one is not supported anymore.

My version is not meant to be used like the way you are using it. You can check the [README](https://github.com/romeovs/gulp-browserify) to see how to use this one. I think it would somewhat like this:

``` js
gulp.task('js', function() {
        gulp.src(['/text-typer.js', '/bootstrap.min.js', 'moment.min.js', '/jquery.noty.js', '/default.js', '/top.js', '/jquery.fitvid.js', '/rrssb.min.js'])
            .pipe(browserify())
            .pipe(concat('footer.js'))
            .pipe(uglify())
            .pipe(rename('footer.min.js'))
            .pipe(gulp.dest('/js/'))
            .pipe(notify('js has just been concat and uglified'));
});

var gulp       = require('gulp')
  , Browserify = require('gulp-browserify')
  ;

var options = {
  entries: ['/text-typer.js', '/bootstrap.min.js', 'moment.min.js', '/jquery.noty.js', '/default.js', '/top.js', '/jquery.fitvid.js', '/rrssb.min.js']
};

gulp.task('js', function() {
  Browserify({
    entries: [ /* main entrypoints here */ ]
    // other options here
  })
  .done(function(strm) {
    strm
      .pipe(concat('footer.js'))
      .pipe(uglify())
      .pipe(rename('footer.min.js'))
      .pipe(gulp.dest('/js/'))
      .pipe(notify('js has just been concat and uglified'));
   }); 
```
